name: icesspool
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  form_builder_validators: ^9.0.0
  flutter_form_builder: ^9.0.0
  flutter_svg: ^1.1.5
  image_picker: ^0.8.5+3
  video_player: ^2.4.7
  introduction_screen: ^3.1.1
  onboarding: ^3.1.0
  google_sign_in: ^5.4.2
  firebase_auth: ^4.2.4
  provider: ^6.0.5
  firebase_core: ^2.4.1
  shared_preferences: ^2.0.15
  # share_plus: ^7.1.0 

  geolocator: ^9.0.2
  firebase_messaging: ^14.2.1
  sizer: ^2.0.15
  geocoding: ^2.1.0
  intl: ^0.18.0
  internet_connection_checker: ^1.0.0+1
  mask_text_input_formatter: ^2.5.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.1.14
  package_info: ^2.0.2
  upgrader: ^7.1.0
  esys_flutter_share_plus: ^2.2.0


 

dev_dependencies: 
 # flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
#flutter clean && flutter pub get &&  flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.2.11


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png


flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    
    - assets/ca/lets-encrypt-r3.pem


