// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLosrEZTpX17fJq7ZCm9DMNuJhB2CytKA',
    appId: '1:1064378824508:web:1571cd2d9c6306bcde9039',
    messagingSenderId: '1064378824508',
    projectId: 'icesspool',
    authDomain: 'icesspool.firebaseapp.com',
    storageBucket: 'icesspool.appspot.com',
    measurementId: 'G-5BMGJQ1SK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGr7iroeZlvpaWJMoHzYhJZXWNPkxmdkI',
    appId: '1:1064378824508:android:fac18c4406fac0d3de9039',
    messagingSenderId: '1064378824508',
    projectId: 'icesspool',
    storageBucket: 'icesspool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjsdJLw3fdDdfOGy6Gv3vgRk6zwlZMRy4',
    appId: '1:1064378824508:ios:debb826eb037b1f2de9039',
    messagingSenderId: '1064378824508',
    projectId: 'icesspool',
    storageBucket: 'icesspool.appspot.com',
    iosClientId:
        '1064378824508-cmnhtu8aq3drress9tt615ti3pnscohe.apps.googleusercontent.com',
    iosBundleId: 'com.sanitation.report.sanitationReportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjsdJLw3fdDdfOGy6Gv3vgRk6zwlZMRy4',
    appId: '1:1064378824508:ios:debb826eb037b1f2de9039',
    messagingSenderId: '1064378824508',
    projectId: 'icesspool',
    storageBucket: 'icesspool.appspot.com',
    iosClientId:
        '1064378824508-cmnhtu8aq3drress9tt615ti3pnscohe.apps.googleusercontent.com',
    iosBundleId: 'com.sanitation.report.sanitationReportApp',
  );
}
